### PR TITLE
Colored cloze cards + better displaying of code blocks + escaped $ + more versatile usage of cloze + better support for nightMode

### PR DESCRIPTION
**Pull request by alexthillen**

### CODE REVIEW

**Comment by drthillen** [comment]
https://github.com/drthillen/Anki-KaTeX-Markdown/releases/tag/release%2F7

**Comment by alexthillen** [comment]
fixes #40

**Comment by Jwrede** [comment]
Hey this looks promising thanks for the effort! Right now I don't have to time to look over it but do you want me to look at it and merge it to my main branch and upload it to anki as soon as I have time and if it works? Of course I'll give credits where credit is due

**Comment by alexthillen** [comment]
I'll try to tackle a few subtleties in the upcoming days if I get the time, once stable it should be ready for merge. The following screenshots, should give a feel of what we can expect + limitations.

image

image
   
image

**Comment by Jwrede** [comment]
Take as much time as you need and just tell me when you're done :)

**Comment by alexthillen** [comment]
it should be ready for review - you can test the release 16 on the fork [Link](https://github.com/alexthillen/Anki-KaTeX-Markdown/releases/tag/release%2F16). Let me know if you find a bug. It will create a new card type. :)

**Comment by Jwrede** [comment]
Hey Alex, wow you're fast, sorry I will be on vacation for the next week but I'll look at it right after, thanks so much for all your work!

**Comment by Jwrede** [comment]
Hey Alex, 

Sorry for taking so long. I decided against merging your Pull Request because I'm afraid that if I do so, I'll destroy all customization people did to their local version of this Addon. If it's okay for you I'd mark this Addon as deprecated and Link your Version as the one that is being maintained? Totally understand if you don't have time to maintain this but if you do I'd just change the Addon on Ankiweb to "Markdown and KaTeX Support (depricated)" and link to yours. You can change the title to "Markdown and KaTeX Support" then.

Thanks for your effort!

**Comment by alexthillen** [comment]
Hi there, thanks for getting back to me!

We can do it anyway you like. I should have the time to maintain :) 
Installing the extension now, should be creating new card types called Katex and Markdown Basic/Cloze (Color). The old cards which should be saved under "Katex and Markdown Basic/Cloze" should still be available to the user with their customizations if I'm not overseeing something?

image

**Comment by alexthillen** [comment]
Updated the Anki add on (https://ankiweb.net/shared/info/1786114227) and changed the Readme a bit :)

**Pull request closed without merging**
